version: "2"

services:

  inv-rest:
    build: ./rest
    hostname: inv-rest
    ports:
      - "8080:8080"
      - "7000:7000"
    expose:
      - 8080
      - 7000
    networks:
      - inv-parent

  inv-db:
      build: ./db
      hostname: inv-db
      ports:
        - "5432:5432"
      expose:
        - 5432
      networks:
        - inv-parent

networks:
  inv-parent:
    driver: bridge


